# Generated by Django 4.1.3 on 2022-11-23 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blocks",
                    models.CharField(
                        choices=[("BlockA", "A"), ("BlockB", "B"), ("BlockC", "C")],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "block",
            },
        ),
        migrations.CreateModel(
            name="CarsBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_number", models.IntegerField()),
                ("taken", models.BooleanField(default=False)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="carsdata.block"
                    ),
                ),
            ],
            options={
                "db_table": "cars_model",
            },
        ),
    ]
