# Generated by Django 4.1.3 on 2022-11-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carsdata", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carsblock",
            name="user",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
