# Generated by Django 4.1.3 on 2022-12-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carsdata", "0002_carsblock_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="carsblock",
            name="car_number",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
