# Generated by Django 4.1.3 on 2022-12-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carsdata", "0003_carsblock_car_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carsblock",
            name="car_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
