# Generated by Django 4.1.3 on 2022-12-19 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("carsdata", "0004_alter_carsblock_car_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="WishListBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blocks",
                    models.CharField(
                        choices=[("BlockA", "A"), ("BlockB", "B"), ("BlockC", "C")],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "wish_list_block",
            },
        ),
        migrations.CreateModel(
            name="WishListCarsBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.IntegerField(blank=True, null=True)),
                ("seat_number", models.IntegerField()),
                ("taken", models.BooleanField(default=False)),
                ("car_number", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="carsdata.wishlistblock",
                    ),
                ),
            ],
            options={
                "db_table": "wish_list_cars_model",
            },
        ),
    ]
