# Generated by Django 4.1.3 on 2023-01-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carsdata", "0006_carsblock_date_time_wishlistcarsblock_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="carsblock",
            name="date_time_drop",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wishlistcarsblock",
            name="date_time_drop",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
